version: '3'
services:
  ionic:
    container_name: ionic_container
    build: ./docker/node
    ports:
      - "0.0.0.0:8100:8100" # ionic dev server
    tty: true
    volumes:
      - "./app:/var/www/app:rw"
  android_build:
    container_name: android_build_container
    environment:
      TZ: "Asia/Tokyo"
    build: ./docker/android
    tty: true
    volumes:
      - "./app/platforms/android:/data/app:ro"
